### ISSUE TITLE
Ok to move jupyter/nbcache repo to the Jupyter Attic?

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/nbcache#1]
Hi @rgbkrk , 
Fernando & Brian suggested moving this repo to the Jupyter Attic. Let me know if that is ok with you. 

Thanks!

**Comment by minrk** [comment]
This is part of every nbviewer deployment.

**Comment by minrk** [comment]
I opened #2 adding info to the README, which should clarify that we are using this constantly in nbviewer.

**Comment by JamiesHQ** [comment]
@ellisonbg @fperez : fyi - nbcache is part of every nbviewer deployment

**Comment by fperez** [comment]
OK, no problem. Thanks!!
